services:
  - type: web
    name: usc-ir-portal
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT demo_app:server
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PORT
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: FLASK_ENV
        value: "production"
      # Add these in Render Dashboard Environment tab:
      # GOOGLE_CLIENT_SECRET (your actual secret)
      # GOOGLE_CLIENT_ID (already in your code)
    healthCheckPath: /

# Alternative simple configuration if render.yaml doesn't work:
# Just add these files to your repo root instead